### ISSUE TITLE
False positive: yandex.ru

### ISSUE THREAD

**Issue by DRSDavidSoft** [Th3M3/blocklists#1]
Hello,

The domain name `yandex.ru` belongs to the Russian [Yandex Search Engine](https://yandex.com/), which is just another search engine like Google, Yahoo, DuckDuckGo, Bing and Baidu.

Since this domain is not used to serve malware, may I ask you to remove it from your list?

Thank you

**Comment by Th3M3** [comment]
many thanks for the hint @DRSDavidSoft.
I have removed it from the list.
