### ISSUE TITLE
mtalk.google.com required by many Android apps

### ISSUE THREAD

**Issue by p1r473** [Th3M3/blocklists#2]
Please remove mtalk.google.com
This had broken a few Android notifications from various apps

**Comment by Th3M3** [comment]
Thanks.
I've also had notification issues on android devices but never thought that it was related to this blocked domains.

I had whitelisted them locally for some days for testing and indeed I must say that you are right, notifications come up now correctly.

**I have removed them all from my block list**

**Comment by p1r473** [comment]
It was a pain to debug this, lol
